Traceback (most recent call last):
  File "sample_viz.py", line 33, in <module>
    pc, _, _ = load_obj(obj_path)
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/pytorch3d/io/obj_io.py", line 221, in load_obj
    return _load_obj(
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/pytorch3d/io/obj_io.py", line 577, in _load_obj
    ) = _parse_obj(f_obj, data_dir)
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/pytorch3d/io/obj_io.py", line 428, in _parse_obj
    lines = [line.strip() for line in f]
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/pytorch3d/io/obj_io.py", line 428, in <listcomp>
    lines = [line.strip() for line in f]
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte