2022-02-08 13:10:38,530 INFO    MainThread:290394 [wandb_setup.py:_flush():71] setting env: {}
2022-02-08 13:10:38,530 INFO    MainThread:290394 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-08 13:10:38,530 INFO    MainThread:290394 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_131038-m8nxb7zu/logs/debug.log
2022-02-08 13:10:38,530 INFO    MainThread:290394 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_131038-m8nxb7zu/logs/debug-internal.log
2022-02-08 13:10:38,530 INFO    MainThread:290394 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f3b2425db20>
2022-02-08 13:10:38,530 INFO    MainThread:290394 [wandb_init.py:init():404] calling init triggers
2022-02-08 13:10:38,530 INFO    MainThread:290394 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-08 13:10:38,530 INFO    MainThread:290394 [wandb_init.py:init():460] starting backend
2022-02-08 13:10:38,530 INFO    MainThread:290394 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-08 13:10:38,532 INFO    MainThread:290394 [backend.py:ensure_launched():216] starting backend process...
2022-02-08 13:10:38,541 INFO    MainThread:290394 [backend.py:ensure_launched():221] started backend process with pid: 290719
2022-02-08 13:10:38,542 INFO    MainThread:290394 [wandb_init.py:init():469] backend started and connected
2022-02-08 13:10:38,553 INFO    MainThread:290394 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-08 13:10:38,553 INFO    MainThread:290394 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-08 13:10:38,553 INFO    MainThread:290394 [wandb_init.py:init():533] updated telemetry
2022-02-08 13:10:38,584 INFO    MainThread:290394 [wandb_init.py:init():563] communicating current version
2022-02-08 13:10:39,243 INFO    MainThread:290394 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-08 13:10:39,245 INFO    MainThread:290394 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-08 13:10:39,488 INFO    MainThread:290394 [wandb_init.py:init():606] starting run threads in backend
2022-02-08 13:10:41,670 INFO    MainThread:290394 [wandb_run.py:_console_start():1810] atexit reg
2022-02-08 13:10:41,670 INFO    MainThread:290394 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-08 13:10:41,670 INFO    MainThread:290394 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-08 13:10:41,671 INFO    MainThread:290394 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-08 13:10:41,671 INFO    MainThread:290394 [wandb_init.py:init():633] run started, returning control to user process
2022-02-08 13:10:41,671 INFO    MainThread:290394 [wandb_run.py:_config_callback():956] config_cb None None {}
2022-02-08 13:10:41,671 INFO    MainThread:290394 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:10:41,671 INFO    MainThread:290394 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:10:41,729 INFO    MainThread:290394 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:10:41,734 INFO    MainThread:290394 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:10:41,734 INFO    MainThread:290394 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:10:41,770 INFO    MainThread:290394 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:10:41,771 INFO    MainThread:290394 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:10:41,772 INFO    MainThread:290394 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:10:41,811 INFO    MainThread:290394 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:10:41,813 INFO    MainThread:290394 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:10:41,813 INFO    MainThread:290394 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:10:41,864 INFO    MainThread:290394 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:10:42,247 INFO    MainThread:290394 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:10:42,248 INFO    MainThread:290394 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:10:43,000 INFO    MainThread:290394 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:10:43,903 INFO    MainThread:290394 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:10:43,903 INFO    MainThread:290394 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:11:13,961 INFO    MainThread:290394 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:11:14,051 INFO    MainThread:290394 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:11:14,051 INFO    MainThread:290394 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:11:16,266 INFO    MainThread:290394 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:11:16,267 INFO    MainThread:290394 [wandb_run.py:finish():1457] finishing run nelsonsw5/objdet_GT_Viz/m8nxb7zu
2022-02-08 13:11:16,268 INFO    MainThread:290394 [jupyter.py:save_history():429] not saving jupyter history
2022-02-08 13:11:16,268 INFO    MainThread:290394 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:11:16,268 INFO    MainThread:290394 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-08 13:11:16,268 INFO    MainThread:290394 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-08 13:11:16,269 INFO    MainThread:290394 [wandb_run.py:_restore():1752] restore
2022-02-08 13:11:19,727 ERROR   MainThread:290394 [wandb_run.py:_atexit_cleanup():1798] Problem finishing run
Traceback (most recent call last):
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1934, in _on_finish
    self.history._flush()
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1017, in _history_callback
    self._backend.interface.publish_history(
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 496, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2597, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2679, in val_to_json
    return val.to_json(run)
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 820, in to_json
    json_dict = super(Object3D, self).to_json(run_or_artifact)
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 562, in to_json
    assert (
AssertionError: We don't support referring to media files across runs.
